return {
	{
		match = {
			"how upload audio",
			"how create audio",
			"how make audio"
		},
		question = "How to upload audio?",
		response = "This is question 1 from the FAQ in the About tab!"
	},
	{
		match = {
			"who is gaben",
			"who's gaben",
			"who gaben"
		},
		question = "Who's Gaben?",
		response = "Gaben is the developer of this game. The coder of this game. The OWNER of this game."
	}
}
