return {
	[2128349931] = {"easy", "groove battle"},
	[2128359677] = {"impossible", "bug reporter"},
	[2128373124] = {"hard", "exploiter"},
	[2128370851] = {"medium", "???"},
	[2128421049] = {"easy", "alt + f4"},
	[2129337165] = {"free", "joined"},
	[2129337220] = {"hard", "obsessed"},
	[2141796844] = {"medium", "undertale addict"},
	[2141673520] = {"hard", "birthday"},
	[2142926405] = {"hard", "suggester"},
	[2143193454] = {"extraordinary", "april fooled"},

	[2128350906] = {"medium", "witnessed gaben"},
	[2128352757] = {"hard", "witnessed tophat"},
	[2128496513] = {"hard", "witnessed fire"},
	[2128352761] = {"impossible", "witnessed mario"}
}
