return {
	[2129337165] = "Join the game!",
	[2128349931] = "Find the gif of the funny person dancing.",
	[2128350906] = "Have Gaben in your server. (owner)",
	[2128352757] = "Have Tophat in your server. (group owner)",
	[2128496513] = "Have Fire in your server. (game designer)",
	[2128352761] = "Have mario118118 in your server. (developer of Obby Creator)",
	[2128359677] = "Get this badge by reporting a bug to Gaben.",
	[2128370851] = "This badge is quite tricky to get. Good luck getting it!",
	[2128373124] = "Use exploits in this game (why??)",
	[2128421049] = "Press Alt + F4.",
	[2129337220] = "Listen to the same song for an hour without pausing.",
	[2141673520] = "Play on Gaben's birthday! (7th March)",
	[2141796844] = "Listen to an Undertale song for ten minutes without pausing.",
	[2142926405] = "Suggest a good feature and have it added into the game!",
--	[2143193454] = "Only thy noble canst achieve this badge."
}
