local unicode = require(game.ReplicatedStorage.modules.unicode)

return {
	"THIS GAME HAS BEEN ABANDONED!!!",
	"Customize your chat appearance in chat in the Settings!",
	"Use /cmds to view all available commands!",
	"This game officialy has lore!",
	"mario118118 only joined the game once!",
	"Data issues? No worries! Reset your data in the Settings.",
	"Press ALT + F4 for a cool badge!",
	"wow it's the uh empire state building",
	"Type <b>april fooled!</b> in chat to get the april fooled badge!",
	"Type <b>john pork</b> in chat for a cool easter egg!"
}
